### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by ghost** [xoviat/build-python-flint#3]
Mac OSX is in fact my weakest area, so I have little chance of fixing these builds on my own.

**Comment by isuruf** [comment]
I might be able to help. Can you trigger a travis build after removing the piping to /dev/null in https://github.com/xoviat/build-python-flint/blob/master/build_dependencies.sh

**Comment by ghost** [comment]
Build is at https://travis-ci.org/xoviat/build-python-flint/builds/285825682?utm_source=github_status&utm_medium=notification. Good luck!

**Comment by ghost** [comment]
Fixed.
